---
apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  selector:
    app: frontend
  ports:
    - port: 9090
      targetPort: 9090
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: frontend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
      annotations:
        consul.hashicorp.com/connect-inject: 'true'
        consul.hashicorp.com/enable-metrics-merging: "false"
        # consul.hashicorp.com/connect-service-upstreams: 'fake-service:9091, jsonplaceholder-http:9092'
        consul.hashicorp.com/connect-service-upstreams: 'fake-service-finance:9091'
    spec:
      serviceAccountName: frontend
      containers:
        - name: frontend
          image: panchalravi/fake-service:0.24.2
          ports:
            - containerPort: 8080
          env:
            - name: 'LISTEN_ADDR'
              value: '0.0.0.0:9090'
            - name: 'UPSTREAM_URIS'
              # value: 'http://www.google.com.sg'
              value: 'http://localhost:9091'
            - name: 'NAME'
              value: 'frontend'
            - name: 'MESSAGE'
              value: 'Hello World'
          securityContext:
            privileged: true
