apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    meta.helm.sh/release-name: rp-cpeer-consul-server
    meta.helm.sh/release-namespace: consul
  generation: 1
  labels:
    app: consul
    app.kubernetes.io/managed-by: Helm
    chart: consul-helm
    component: server-acl-init
    heritage: Helm
    release: rp-cpeer-consul-server
  name: consul-server-acl-init
  namespace: consul
spec:
  backoffLimit: 6
  completionMode: NonIndexed
  completions: 1
  parallelism: 1
  selector:
    matchLabels:
      controller-uid: 47cf67df-6058-4b18-bb28-6ab79e63b7c5
  suspend: false
  template:
    metadata:
      annotations:
        consul.hashicorp.com/connect-inject: "false"
      creationTimestamp: null
      labels:
        app: consul
        chart: consul-helm
        component: server-acl-init
        controller-uid: 47cf67df-6058-4b18-bb28-6ab79e63b7c5
        job-name: consul-server-acl-init
        release: rp-cpeer-consul-server
      name: consul-server-acl-init
    spec:
      containers:
      - command:
        - /bin/sh
        - -ec
        - |
          CONSUL_FULLNAME="consul"

          consul-k8s-control-plane server-acl-init \
            -log-level=debug \
            -log-json=false \
            -resource-prefix=${CONSUL_FULLNAME} \
            -k8s-namespace=consul \
            -set-server-tokens=true \
            -consul-api-timeout=5s \
            -server-address="${CONSUL_FULLNAME}-server-0.${CONSUL_FULLNAME}-server.${NAMESPACE}.svc" \
            -use-https \
            -consul-ca-cert=/consul/tls/ca/tls.crt \
            -server-port=8501 \
            -enable-partitions=true \
            -partition=default \
            -allow-dns=true \
            -connect-inject=true \
            -mesh-gateway=true \
            -terminating-gateway-name="https-terminating-gateway.default" \
            -acl-binding-rule-selector=serviceaccount.name!=default \
            -create-enterprise-license-token=true \
            -controller=true \
            -enable-namespaces=true \
            -consul-inject-destination-namespace=default \
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        image: hashicorp/consul-k8s-control-plane:0.46.0
        imagePullPolicy: IfNotPresent
        name: post-install-job
        resources:
          limits:
            cpu: 50m
            memory: 50Mi
          requests:
            cpu: 50m
            memory: 50Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /consul/tls/ca
          name: consul-ca-cert
          readOnly: true
      dnsPolicy: ClusterFirst
      restartPolicy: Never
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: consul-server-acl-init
      serviceAccountName: consul-server-acl-init
      terminationGracePeriodSeconds: 30
      volumes:
      - name: consul-ca-cert
        secret:
          defaultMode: 420
          items:
          - key: tls.crt
            path: tls.crt
          secretName: consul-ca-cert
