---
apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceIntentions
metadata:
  name: backend
spec:
  destination:
    name: backend
  sources:
    - name: web
      action: allow
    - name: frontend
      peer: dc1a-default
      action: allow
    # - name: ingress-gateway
    #   action: allow