apiVersion: consul.hashicorp.com/v1alpha1
kind: ExportedServices
metadata:
  name: default ## The name of the partition containing the service
spec:
  services:
  - name: external-service ## The name of the service you want to export
    consumers:
    - peer: dc1a-default ## The name of the peering connection that receives the service
  - name: backend
    consumers:
    - peer: dc1a-default