apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceSplitter
metadata:
  name: backend
spec:
  splits:
    - weight: 50
      service: backend-dc1a-default
    - weight: 50
      service: backend-dc1b-default
