apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceResolver
metadata:
  name: product
spec:
  connectTimeout: 15s
  failover:
    '*':
      targets:
        - peer: dc1a-default
          service: product
          namespace: default
