---
apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  selector:
    app: frontend
  ports:
    - port: 8080
      targetPort: 9090
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: frontend
---
apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceDefaults
metadata:
  name: frontend
spec:
  protocol: "http"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
      annotations:
        consul.hashicorp.com/connect-inject: 'true'
        # consul.hashicorp.com/connect-service-upstreams: 'backend:9091'
        # consul.hashicorp.com/connect-service-upstreams: 'external-service.svc.default.ns.dc2-default.peer:9091,backend.svc.default.ns.dc2-default.peer:9092'
        consul.hashicorp.com/enable-metrics-merging: "false"
    spec:
      serviceAccountName: frontend
      containers:
        - name: frontend
          image: panchalravi/fake-service:0.24.2
          ports:
            - containerPort: 9090
          env:
            - name: 'LISTEN_ADDR'
              value: '0.0.0.0:9090'
            - name: 'UPSTREAM_URIS'
              # value: 'http://backend.virtual.default.ns.dev1.ap.shared.dc.consul'
              # value: 'http://backend.virtual.default.ns.hr.ap.dc2-finance.peer.consul'
              # value: 'http://backend.virtual.hr.ap.dc2-finance.peer.consul'
              # value: 'http://backend.virtual.default.dc2-default.consul,http://external-service.virtual.default.dc2-default.consul'
              # value: 'http://backend.virtual.dc2-default.peer.consul'
              # value: 'http://backend.virtual.consul'
              # value: 'http://backend.virtual.dc1a-default.consul,http://backend.virtual.dc1b-default.consul'
              # value: 'http://backend.virtual.backend.ns.consul'
              value: 'http://backend.backend'
            - name: 'NAME'
              value: 'frontend'
            - name: 'MESSAGE'
              value: 'Hello World'
          # securityContext:
          #   privileged: true
